//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: init_service.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `ServiceClient`, then call methods of this protocol to make API calls.
public protocol ServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: ServiceClientInterceptorFactoryProtocol? { get }

  func getInitialConfig(
    _ request: GetInitialConfigRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<GetInitialConfigRequest, GetInitialConfigResponse>
}

extension ServiceClientProtocol {
  public var serviceName: String {
    return "Service"
  }

  /// Unary call to GetInitialConfig
  ///
  /// - Parameters:
  ///   - request: Request to send to GetInitialConfig.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getInitialConfig(
    _ request: GetInitialConfigRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<GetInitialConfigRequest, GetInitialConfigResponse> {
    return self.makeUnaryCall(
      path: ServiceClientMetadata.Methods.getInitialConfig.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetInitialConfigInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension ServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "ServiceNIOClient")
public final class ServiceClient: ServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: ServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: ServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the Service service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct ServiceNIOClient: ServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: ServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the Service service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol ServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: ServiceClientInterceptorFactoryProtocol? { get }

  func makeGetInitialConfigCall(
    _ request: GetInitialConfigRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<GetInitialConfigRequest, GetInitialConfigResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension ServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return ServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: ServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeGetInitialConfigCall(
    _ request: GetInitialConfigRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<GetInitialConfigRequest, GetInitialConfigResponse> {
    return self.makeAsyncUnaryCall(
      path: ServiceClientMetadata.Methods.getInitialConfig.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetInitialConfigInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension ServiceAsyncClientProtocol {
  public func getInitialConfig(
    _ request: GetInitialConfigRequest,
    callOptions: CallOptions? = nil
  ) async throws -> GetInitialConfigResponse {
    return try await self.performAsyncUnaryCall(
      path: ServiceClientMetadata.Methods.getInitialConfig.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetInitialConfigInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct ServiceAsyncClient: ServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: ServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol ServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'getInitialConfig'.
  func makeGetInitialConfigInterceptors() -> [ClientInterceptor<GetInitialConfigRequest, GetInitialConfigResponse>]
}

public enum ServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Service",
    fullName: "Service",
    methods: [
      ServiceClientMetadata.Methods.getInitialConfig,
    ]
  )

  public enum Methods {
    public static let getInitialConfig = GRPCMethodDescriptor(
      name: "GetInitialConfig",
      path: "/Service/GetInitialConfig",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol ServiceProvider: CallHandlerProvider {
  var interceptors: ServiceServerInterceptorFactoryProtocol? { get }

  func getInitialConfig(request: GetInitialConfigRequest, context: StatusOnlyCallContext) -> EventLoopFuture<GetInitialConfigResponse>
}

extension ServiceProvider {
  public var serviceName: Substring {
    return ServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetInitialConfig":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<GetInitialConfigRequest>(),
        responseSerializer: ProtobufSerializer<GetInitialConfigResponse>(),
        interceptors: self.interceptors?.makeGetInitialConfigInterceptors() ?? [],
        userFunction: self.getInitialConfig(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol ServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: ServiceServerInterceptorFactoryProtocol? { get }

  func getInitialConfig(
    request: GetInitialConfigRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> GetInitialConfigResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension ServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return ServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return ServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: ServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetInitialConfig":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<GetInitialConfigRequest>(),
        responseSerializer: ProtobufSerializer<GetInitialConfigResponse>(),
        interceptors: self.interceptors?.makeGetInitialConfigInterceptors() ?? [],
        wrapping: { try await self.getInitialConfig(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol ServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'getInitialConfig'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetInitialConfigInterceptors() -> [ServerInterceptor<GetInitialConfigRequest, GetInitialConfigResponse>]
}

public enum ServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Service",
    fullName: "Service",
    methods: [
      ServiceServerMetadata.Methods.getInitialConfig,
    ]
  )

  public enum Methods {
    public static let getInitialConfig = GRPCMethodDescriptor(
      name: "GetInitialConfig",
      path: "/Service/GetInitialConfig",
      type: GRPCCallType.unary
    )
  }
}
