//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: main_service.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Service_MainServiceClient`, then call methods of this protocol to make API calls.
public protocol Service_MainServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Service_MainServiceClientInterceptorFactoryProtocol? { get }

  func getUpdatedURLs(
    _ request: Service_GetUpdatedURLsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Service_GetUpdatedURLsRequest, Service_GetUpdatedURLsResponse>

  func updateUserInfo(
    _ request: Service_UpdateUserInfoRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Service_UpdateUserInfoRequest, SwiftProtobuf.Google_Protobuf_Empty>
}

extension Service_MainServiceClientProtocol {
  public var serviceName: String {
    return "service.MainService"
  }

  /// Unary call to GetUpdatedURLs
  ///
  /// - Parameters:
  ///   - request: Request to send to GetUpdatedURLs.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getUpdatedURLs(
    _ request: Service_GetUpdatedURLsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Service_GetUpdatedURLsRequest, Service_GetUpdatedURLsResponse> {
    return self.makeUnaryCall(
      path: Service_MainServiceClientMetadata.Methods.getUpdatedURLs.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetUpdatedURLsInterceptors() ?? []
    )
  }

  /// Unary call to UpdateUserInfo
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateUserInfo.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func updateUserInfo(
    _ request: Service_UpdateUserInfoRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Service_UpdateUserInfoRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: Service_MainServiceClientMetadata.Methods.updateUserInfo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateUserInfoInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Service_MainServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Service_MainServiceNIOClient")
public final class Service_MainServiceClient: Service_MainServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Service_MainServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Service_MainServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the service.MainService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Service_MainServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Service_MainServiceNIOClient: Service_MainServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Service_MainServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the service.MainService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Service_MainServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Service_MainServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Service_MainServiceClientInterceptorFactoryProtocol? { get }

  func makeGetUpdatedUrlsCall(
    _ request: Service_GetUpdatedURLsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Service_GetUpdatedURLsRequest, Service_GetUpdatedURLsResponse>

  func makeUpdateUserInfoCall(
    _ request: Service_UpdateUserInfoRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Service_UpdateUserInfoRequest, SwiftProtobuf.Google_Protobuf_Empty>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Service_MainServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Service_MainServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Service_MainServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeGetUpdatedUrlsCall(
    _ request: Service_GetUpdatedURLsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Service_GetUpdatedURLsRequest, Service_GetUpdatedURLsResponse> {
    return self.makeAsyncUnaryCall(
      path: Service_MainServiceClientMetadata.Methods.getUpdatedURLs.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetUpdatedURLsInterceptors() ?? []
    )
  }

  public func makeUpdateUserInfoCall(
    _ request: Service_UpdateUserInfoRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Service_UpdateUserInfoRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeAsyncUnaryCall(
      path: Service_MainServiceClientMetadata.Methods.updateUserInfo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateUserInfoInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Service_MainServiceAsyncClientProtocol {
  public func getUpdatedURLs(
    _ request: Service_GetUpdatedURLsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Service_GetUpdatedURLsResponse {
    return try await self.performAsyncUnaryCall(
      path: Service_MainServiceClientMetadata.Methods.getUpdatedURLs.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetUpdatedURLsInterceptors() ?? []
    )
  }

  public func updateUserInfo(
    _ request: Service_UpdateUserInfoRequest,
    callOptions: CallOptions? = nil
  ) async throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try await self.performAsyncUnaryCall(
      path: Service_MainServiceClientMetadata.Methods.updateUserInfo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateUserInfoInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Service_MainServiceAsyncClient: Service_MainServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Service_MainServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Service_MainServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Service_MainServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'getUpdatedURLs'.
  func makeGetUpdatedURLsInterceptors() -> [ClientInterceptor<Service_GetUpdatedURLsRequest, Service_GetUpdatedURLsResponse>]

  /// - Returns: Interceptors to use when invoking 'updateUserInfo'.
  func makeUpdateUserInfoInterceptors() -> [ClientInterceptor<Service_UpdateUserInfoRequest, SwiftProtobuf.Google_Protobuf_Empty>]
}

public enum Service_MainServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MainService",
    fullName: "service.MainService",
    methods: [
      Service_MainServiceClientMetadata.Methods.getUpdatedURLs,
      Service_MainServiceClientMetadata.Methods.updateUserInfo,
    ]
  )

  public enum Methods {
    public static let getUpdatedURLs = GRPCMethodDescriptor(
      name: "GetUpdatedURLs",
      path: "/service.MainService/GetUpdatedURLs",
      type: GRPCCallType.unary
    )

    public static let updateUserInfo = GRPCMethodDescriptor(
      name: "UpdateUserInfo",
      path: "/service.MainService/UpdateUserInfo",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Service_MainServiceProvider: CallHandlerProvider {
  var interceptors: Service_MainServiceServerInterceptorFactoryProtocol? { get }

  func getUpdatedURLs(request: Service_GetUpdatedURLsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Service_GetUpdatedURLsResponse>

  func updateUserInfo(request: Service_UpdateUserInfoRequest, context: StatusOnlyCallContext) -> EventLoopFuture<SwiftProtobuf.Google_Protobuf_Empty>
}

extension Service_MainServiceProvider {
  public var serviceName: Substring {
    return Service_MainServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetUpdatedURLs":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Service_GetUpdatedURLsRequest>(),
        responseSerializer: ProtobufSerializer<Service_GetUpdatedURLsResponse>(),
        interceptors: self.interceptors?.makeGetUpdatedURLsInterceptors() ?? [],
        userFunction: self.getUpdatedURLs(request:context:)
      )

    case "UpdateUserInfo":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Service_UpdateUserInfoRequest>(),
        responseSerializer: ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        interceptors: self.interceptors?.makeUpdateUserInfoInterceptors() ?? [],
        userFunction: self.updateUserInfo(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Service_MainServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Service_MainServiceServerInterceptorFactoryProtocol? { get }

  func getUpdatedURLs(
    request: Service_GetUpdatedURLsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Service_GetUpdatedURLsResponse

  func updateUserInfo(
    request: Service_UpdateUserInfoRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> SwiftProtobuf.Google_Protobuf_Empty
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Service_MainServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Service_MainServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Service_MainServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Service_MainServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetUpdatedURLs":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Service_GetUpdatedURLsRequest>(),
        responseSerializer: ProtobufSerializer<Service_GetUpdatedURLsResponse>(),
        interceptors: self.interceptors?.makeGetUpdatedURLsInterceptors() ?? [],
        wrapping: { try await self.getUpdatedURLs(request: $0, context: $1) }
      )

    case "UpdateUserInfo":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Service_UpdateUserInfoRequest>(),
        responseSerializer: ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        interceptors: self.interceptors?.makeUpdateUserInfoInterceptors() ?? [],
        wrapping: { try await self.updateUserInfo(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Service_MainServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'getUpdatedURLs'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetUpdatedURLsInterceptors() -> [ServerInterceptor<Service_GetUpdatedURLsRequest, Service_GetUpdatedURLsResponse>]

  /// - Returns: Interceptors to use when handling 'updateUserInfo'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateUserInfoInterceptors() -> [ServerInterceptor<Service_UpdateUserInfoRequest, SwiftProtobuf.Google_Protobuf_Empty>]
}

public enum Service_MainServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MainService",
    fullName: "service.MainService",
    methods: [
      Service_MainServiceServerMetadata.Methods.getUpdatedURLs,
      Service_MainServiceServerMetadata.Methods.updateUserInfo,
    ]
  )

  public enum Methods {
    public static let getUpdatedURLs = GRPCMethodDescriptor(
      name: "GetUpdatedURLs",
      path: "/service.MainService/GetUpdatedURLs",
      type: GRPCCallType.unary
    )

    public static let updateUserInfo = GRPCMethodDescriptor(
      name: "UpdateUserInfo",
      path: "/service.MainService/UpdateUserInfo",
      type: GRPCCallType.unary
    )
  }
}
