//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: main_service.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `ServiceClient`, then call methods of this protocol to make API calls.
public protocol ServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: ServiceClientInterceptorFactoryProtocol? { get }

  func getUpdatedURLs(
    _ request: GetUpdatedURLsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<GetUpdatedURLsRequest, GetUpdatedURLsResponse>
}

extension ServiceClientProtocol {
  public var serviceName: String {
    return "Service"
  }

  /// Unary call to GetUpdatedURLs
  ///
  /// - Parameters:
  ///   - request: Request to send to GetUpdatedURLs.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getUpdatedURLs(
    _ request: GetUpdatedURLsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<GetUpdatedURLsRequest, GetUpdatedURLsResponse> {
    return self.makeUnaryCall(
      path: ServiceClientMetadata.Methods.getUpdatedURLs.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetUpdatedURLsInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension ServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "ServiceNIOClient")
public final class ServiceClient: ServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: ServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: ServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the Service service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct ServiceNIOClient: ServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: ServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the Service service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol ServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: ServiceClientInterceptorFactoryProtocol? { get }

  func makeGetUpdatedUrlsCall(
    _ request: GetUpdatedURLsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<GetUpdatedURLsRequest, GetUpdatedURLsResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension ServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return ServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: ServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeGetUpdatedUrlsCall(
    _ request: GetUpdatedURLsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<GetUpdatedURLsRequest, GetUpdatedURLsResponse> {
    return self.makeAsyncUnaryCall(
      path: ServiceClientMetadata.Methods.getUpdatedURLs.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetUpdatedURLsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension ServiceAsyncClientProtocol {
  public func getUpdatedURLs(
    _ request: GetUpdatedURLsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> GetUpdatedURLsResponse {
    return try await self.performAsyncUnaryCall(
      path: ServiceClientMetadata.Methods.getUpdatedURLs.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetUpdatedURLsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct ServiceAsyncClient: ServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: ServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: ServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol ServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'getUpdatedURLs'.
  func makeGetUpdatedURLsInterceptors() -> [ClientInterceptor<GetUpdatedURLsRequest, GetUpdatedURLsResponse>]
}

public enum ServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Service",
    fullName: "Service",
    methods: [
      ServiceClientMetadata.Methods.getUpdatedURLs,
    ]
  )

  public enum Methods {
    public static let getUpdatedURLs = GRPCMethodDescriptor(
      name: "GetUpdatedURLs",
      path: "/Service/GetUpdatedURLs",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol ServiceProvider: CallHandlerProvider {
  var interceptors: ServiceServerInterceptorFactoryProtocol? { get }

  func getUpdatedURLs(request: GetUpdatedURLsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<GetUpdatedURLsResponse>
}

extension ServiceProvider {
  public var serviceName: Substring {
    return ServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetUpdatedURLs":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<GetUpdatedURLsRequest>(),
        responseSerializer: ProtobufSerializer<GetUpdatedURLsResponse>(),
        interceptors: self.interceptors?.makeGetUpdatedURLsInterceptors() ?? [],
        userFunction: self.getUpdatedURLs(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol ServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: ServiceServerInterceptorFactoryProtocol? { get }

  func getUpdatedURLs(
    request: GetUpdatedURLsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> GetUpdatedURLsResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension ServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return ServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return ServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: ServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetUpdatedURLs":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<GetUpdatedURLsRequest>(),
        responseSerializer: ProtobufSerializer<GetUpdatedURLsResponse>(),
        interceptors: self.interceptors?.makeGetUpdatedURLsInterceptors() ?? [],
        wrapping: { try await self.getUpdatedURLs(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol ServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'getUpdatedURLs'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetUpdatedURLsInterceptors() -> [ServerInterceptor<GetUpdatedURLsRequest, GetUpdatedURLsResponse>]
}

public enum ServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Service",
    fullName: "Service",
    methods: [
      ServiceServerMetadata.Methods.getUpdatedURLs,
    ]
  )

  public enum Methods {
    public static let getUpdatedURLs = GRPCMethodDescriptor(
      name: "GetUpdatedURLs",
      path: "/Service/GetUpdatedURLs",
      type: GRPCCallType.unary
    )
  }
}
